/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.luchici.java-conventions")
}

dependencies {

    compileOnly("org.projectlombok:lombok:1.18.28")
    annotationProcessor("org.projectlombok:lombok:1.18.28")
    testCompileOnly("org.projectlombok:lombok:1.18.28")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.28")

    api("org.springframework.boot:spring-boot-starter-data-jpa:2.7.4")
    api("org.postgresql:postgresql:42.3.7")
    api("org.springframework.boot:spring-boot-starter-web:2.7.4")
    api("org.flywaydb:flyway-core:9.19.1")
    testImplementation("org.testcontainers:junit-jupiter:1.18.1")
    testImplementation("org.testcontainers:testcontainers:1.18.1")
    testImplementation("io.cucumber:cucumber-java:7.12.0")
    testImplementation("io.cucumber:cucumber-java8:7.12.0")
    testImplementation("io.cucumber:cucumber-junit:7.12.0")
    testImplementation("io.cucumber:cucumber-spring:7.12.0")
}

description = "CityService"
