/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    id("com.github.luchici.java-conventions")
    id("io.spring.dependency-management") version "1.1.0"
    id("org.springframework.boot") version "2.7.4"
}

dependencies {

    compileOnly("org.projectlombok:lombok:1.18.28")
    annotationProcessor("org.projectlombok:lombok:1.18.28")
    testCompileOnly("org.projectlombok:lombok:1.18.28")
    testAnnotationProcessor("org.projectlombok:lombok:1.18.28")

    implementation("org.springframework.cloud:spring-cloud-starter-openfeign:3.1.8")

    api("org.springframework.boot:spring-boot-starter-thymeleaf")
    api("org.springframework.boot:spring-boot-starter-web")
    api("nz.net.ultraq.thymeleaf:thymeleaf-layout-dialect")
    testImplementation("com.squareup.okhttp3:okhttp:4.0.1")
    testImplementation("com.squareup.okhttp3:mockwebserver:4.0.1")
}

description = "Frontend-Thymeleaf"
