/*
 * This file was generated by the Gradle 'init' task.
 *
 * This project uses @Incubating APIs which are subject to change.
 */

plugins {
    `java-library`
    `maven-publish`
}

repositories {
    mavenLocal()
    maven {
        url = uri("https://repo.maven.apache.org/maven2/")
    }
}

dependencies {
    api("org.springframework.boot:spring-boot-starter-json:2.7.4")
    api("org.springframework.boot:spring-boot-devtools:2.7.4")
    api("org.springframework.boot:spring-boot-starter-validation:2.7.4")
    api("org.projectlombok:lombok:1.18.24")
    api("com.google.code.findbugs:jsr305:3.0.2")
    api("com.fasterxml.jackson.datatype:jackson-datatype-jsr310:2.15.2")
    api("org.modelmapper:modelmapper:3.1.1")
    testImplementation("org.testcontainers:postgresql:1.18.0")
    testImplementation("org.springframework.boot:spring-boot-starter-test:2.7.4")
}

group = "com.github.luchici"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

publishing {
    publications.create<MavenPublication>("maven") {
        from(components["java"])
    }
}

tasks.withType<JavaCompile>() {
    options.encoding = "UTF-8"
}

tasks.withType<Javadoc>() {
    options.encoding = "UTF-8"
}
